# rfc.yml
# Author: Matt Dumler <mattd3v@pm.me> (https://mattdumler.app)
# Edited: April 26, 2020
# License: MIT

name: Build XML RFC

on: push
jobs:

  bundle:
    name: Bundle Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bundle script
        run: ./bundle
      - uses: actions/upload-artifact@v1
        with:
          name: bundle
          path: bundle.mkd

  compile:
    name: Build XML
    runs-on: ubuntu-latest
    needs: bundle
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: bundle
          path: bundle.mkd
      - uses: mattd3v/mkd2xml@master
        with:
          filename: bundle.mkd
      - uses: actions/upload-artifact@v1
        with:
          name: xml
          path: output

  build:
    name: Build RFC
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: xml
          path: build.xml
      - run: apt install --yes xml2rfc
      - run: xml2rfc build.xml

