# rfc.yml
# Author: Matt Dumler <mattd3v@pm.me> (https://mattdumler.app)
# Edited: April 26, 2020
# License: MIT

name: Build XML RFC

on:
  pull_request:
    - master

jobs:

  bundle:
    name: Bundle Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bundle script
        run: ./bundle
      - uses: actions/upload-artifact@v1
        with:
          name: bundle
          path: bundle.mkd

  build:
    name: Build XML
    runs-on: ubuntu-latest
    needs: bundle
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: bundle
          path: bundle.mkd
      - uses: .github/actions/mkd2xml
        with:
          path: bundle.mkd
